services:
  frontend-prod:
    build: 
      dockerfile: "Dockerfile"
      target: gradient-frontend-prod
    env_file:
      - ".env"
    environment:
      - GRADIENT_BACKEND_SERVER_IP=backend
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:${GRADIENT_FRONTEND_SERVER_PORT}"

  backend-prod:
    build:
      dockerfile: "Dockerfile"
      target: gradient-backend-prod
    env_file:
      - ".env"
    ports:
      - "8080:${GRADIENT_BACKEND_SERVER_PORT}"