services:
  frontend-dev:
    build:
      dockerfile: Dockerfile
      target: gradient-frontend-dev
    env_file:
      - ".env.dev"
    environment:
      - GRADIENT_BACKEND_SERVER_IP=backend-dev
      - HOSTNAME=0.0.0.0
      - WATCHPACK_POLLING=true
      - POLLING_INTERVAL_MS=1000
    ports:
      - "3000:${GRADIENT_FRONTEND_SERVER_PORT}"
    develop:
      watch:
        - action: sync
          path: apps/frontend
          target: /app/apps/frontend
          ignore:
            - node_modules/
            - .next/
            - Dockerfile
        - action: rebuild
          path: apps/frontend/package.json

  backend-dev:
    build:
      dockerfile: Dockerfile
      target: gradient-backend-dev
    env_file:
      - ".env.dev"
    ports:
      - "8080:${GRADIENT_BACKEND_SERVER_PORT}"
    develop:
      watch:
        - action: sync
          path: apps/backend
          target: /app/apps/backend
          ignore:
            - target/
            - .next/
            - Dockerfile
        - action: rebuild
          path: apps/backend/Cargo.toml