FROM ghcr.io/pnpm/pnpm:latest
RUN pnpm runtime set node 22 -g 
WORKDIR /app
COPY apps/frontend apps/frontend
RUN pnpm install --frozen-lockfile -C apps/frontend
ENV WATCHPACK_POLLING=true
EXPOSE 3000
CMD [ "pnpm", "run", "-C", "apps/frontend", "dev" ]